INFO:2020-02-27 09:19:33,810:workflow_proxy.py:executetask:StartNoneEvent is run
INFO:2020-02-27 09:19:33,811:workflow_proxy.py:executetask:request next workflow proxy service.
INFO:2020-02-27 09:19:35,855:workflow_proxy.py:init:parameters are initialized.
INFO:2020-02-27 09:19:35,859:_internal.py:_log:127.0.0.1 - - [27/Feb/2020 09:19:35] "POST /init HTTP/1.1" 200 -
INFO:2020-02-27 09:19:35,864:workflow_proxy.py:executetask:next_run_addresshttp://localhost:5001/init---response: <Response [200]>
INFO:2020-02-27 09:19:37,885:workflow_proxy.py:init:parameters are initialized.
INFO:2020-02-27 09:19:37,888:_internal.py:_log:127.0.0.1 - - [27/Feb/2020 09:19:37] "POST /init HTTP/1.1" 200 -
INFO:2020-02-27 09:19:37,893:workflow_proxy.py:executetask:next_run_addresshttp://localhost:5001/init---response: <Response [200]>
INFO:2020-02-27 09:19:53,191:_internal.py:_log:127.0.0.1 - - [27/Feb/2020 09:19:53] "POST /run HTTP/1.1" 200 -
INFO:2020-02-27 09:28:24,867:_internal.py:_log: * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
INFO:2020-02-27 09:28:29,442:workflow_proxy.py:init:parameters are initialized.
INFO:2020-02-27 09:28:29,446:_internal.py:_log:127.0.0.1 - - [27/Feb/2020 09:28:29] "POST /init HTTP/1.1" 200 -
INFO:2020-02-27 09:28:45,452:workflow_proxy.py:executetask:Task is run
ERROR:2020-02-27 09:28:56,023:app.py:log_exception:Exception on /run [POST]
Traceback (most recent call last):
  File "D:\soft\2019-12-03-python\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\soft\2019-12-03-python\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\soft\2019-12-03-python\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\soft\2019-12-03-python\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\soft\2019-12-03-python\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\soft\2019-12-03-python\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:/code/fudan/python/cpss-process/service/workflow_proxy.py", line 67, in executetask
    executor_resource_instance_id = get_resource_instance_id(executor_resource_id)
  File "D:/code/fudan/python/cpss-process/service/workflow_proxy.py", line 105, in get_resource_instance_id
    app_instance_resources = find_app_instance_resource_by_instance_id().get("resource")
AttributeError: 'NoneType' object has no attribute 'get'
INFO:2020-02-27 09:28:56,035:_internal.py:_log:127.0.0.1 - - [27/Feb/2020 09:28:56] "POST /run HTTP/1.1" 500 -
